[tool.black]
line-length = 119
target-version = ['py38']
extend-exclude = '/(\.git|__pycache__)/'

[tool.isort]
profile = "black"
line_length = 119
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'KODI', 'FIRSTPARTY', 'LOCALFOLDER']
known_kodi = [ 'xbmc', 'xbmcaddon', 'xbmcdrm', 'xbmcgui', 'xbmcmediaimport', 'xbmcplugin', 'xbmcvfs', 'xbmcwsgi' ]
